<!DOCTYPE html><html lang='en'><head><title>[except.special]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Serif'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans'/><link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css2?family=Noto+Sans+Mono'/><link rel='icon' href='icon.png'/><link rel='stylesheet' type='text/css' href='expanded.css' title='Normal'/><link rel='alternate stylesheet' type='text/css' href='colored.css' title='Notes and examples colored'/><link rel='alternate stylesheet' type='text/css' href='normative-only.css' title='Notes and examples hidden'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:50pt'>14</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:65pt'>14.6</a> Special functions <a class='abbr_ref'>[except.special]</a></h2><div id='general' class='section'><h3 ><a class='secnum' href='#general' style='min-width:80pt'>14.6.1</a> General <a class='abbr_ref' href='except.special.general'>[except.special.general]</a></h3><div class='para' id='general-1'><div class='marginalizedparent'><a class='marginalized' href='#general-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/399b93910d0bb6f5632405ad188e9f4aad0ae99a/source/exceptions.tex#L999'>#</a></div><div class='texpara'><div id='general-1.sentence-1' class='sentence'>The function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> (<a href='#except.terminate' title='14.6.2&emsp;The std&#x200b;::&#x200b;terminate function'>[except.<span class='shy'></span>terminate]</a>)
is used by the exception
handling mechanism for coping with errors related to the exception handling
mechanism itself<a class='hidden_link' href='#general-1.sentence-1'>.</a></div> <div id='general-1.sentence-2' class='sentence'>The function
<a href='propagation' title='17.9.7&emsp;Exception propagation&emsp;[propagation]'><span class='texttt'>std&#x200b;::&#x200b;current_<span class='shy'></span>exception()</span></a> and the class
<a href='except.nested' title='17.9.8&emsp;nested_&shy;exception&emsp;[except.nested]'><span class='texttt'>std&#x200b;::&#x200b;nested_<span class='shy'></span>exception</span></a> can be used by a program to
capture the currently handled exception<a class='hidden_link' href='#general-1.sentence-2'>.</a></div></div></div></div><div id='except.terminate' class='section'><h3 ><a class='secnum' href='#except.terminate' style='min-width:80pt'>14.6.2</a> The <span class='texttt'>std&#x200b;::&#x200b;terminate</span> function <a class='abbr_ref' href='except.terminate'>[except.terminate]</a></h3><div class='para' id='except.terminate-1'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/399b93910d0bb6f5632405ad188e9f4aad0ae99a/source/exceptions.tex#L1010'>#</a></div><div class='texpara'><div id='except.terminate-1.sentence-1' class='sentence'><a class='index' id=':terminate'></a>Some errors in a program cannot be recovered from, such as when an exception
is not handled or a <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>thread</span> object is destroyed while its thread
function is still executing<a class='hidden_link' href='#except.terminate-1.sentence-1'>.</a></div> <div id='except.terminate-1.sentence-2' class='sentence'>In such cases,
the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> (<a href='exception.terminate' title='17.9.5&emsp;Abnormal termination'>[exception.<span class='shy'></span>terminate]</a>) is invoked<a class='hidden_link' href='#except.terminate-1.sentence-2'>.</a></div> <div id='except.terminate-note-1' class='note'><div class='texpara'>[<i>Note&nbsp;<a href='#except.terminate-note-1'>1</a></i>:&ensp;<div id='except.terminate-1.sentence-3' class='sentence'>These situations are:
<a class='index' id=':terminate,called'></a><ul class='itemize'><li id='except.terminate-1.1'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.1'>(1.1)</a></div>when the exception handling mechanism, after completing
the initialization of the exception object
but before
activation of a handler for the exception (<a href='except.throw' title='14.2&emsp;Throwing an exception'>[except.<span class='shy'></span>throw]</a>),
calls a function that exits
via an exception, or</li><li id='except.terminate-1.2'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.2'>(1.2)</a></div>when the exception handling mechanism cannot find a handler for a thrown exception (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>), or</li><li id='except.terminate-1.3'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.3'>(1.3)</a></div>when the search for a <a href='except.handle' title='14.4&emsp;Handling an exception&emsp;[except.handle]'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec' title='14.5&emsp;Exception specifications&emsp;[except.spec]'>exception specification</a>, or</li><li id='except.terminate-1.4'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.4'>(1.4)</a></div>when the destruction of an object during <a href='except.ctor#def:stack_unwinding' title='14.3&emsp;Stack unwinding&emsp;[except.ctor]'>stack unwinding</a>
terminates by throwing an exception, or</li><li id='except.terminate-1.5'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.5'>(1.5)</a></div>when initialization of a non-block
variable with static or thread storage duration (<a href='basic.start.dynamic' title='6.9.3.3&emsp;Dynamic initialization of non-block variables'>[basic.<span class='shy'></span>start.<span class='shy'></span>dynamic]</a>)
exits via an exception, or</li><li id='except.terminate-1.6'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.6'>(1.6)</a></div>when destruction of an object with static or thread storage duration exits
via an exception (<a href='basic.start.term' title='6.9.3.4&emsp;Termination'>[basic.<span class='shy'></span>start.<span class='shy'></span>term]</a>), or</li><li id='except.terminate-1.7'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.7'>(1.7)</a></div>when execution of a function registered with
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>atexit</span> or <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>at_<span class='shy'></span>quick_<span class='shy'></span>exit</span>
exits via an exception (<a href='support.start.term' title='17.5&emsp;Startup and termination'>[support.<span class='shy'></span>start.<span class='shy'></span>term]</a>), or</li><li id='except.terminate-1.8'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.8'>(1.8)</a></div>when a
<a href='expr.throw#nt:throw-expression' title='7.6.18&emsp;Throwing an exception&emsp;[expr.throw]'><span id='ntref:throw-expression'><span class='textsf'><i >throw-expression</i></span></span></a> (<a href='expr.throw' title='7.6.18&emsp;Throwing an exception'>[expr.<span class='shy'></span>throw]</a>)
with no operand attempts to rethrow an exception and no exception is being
handled (<a href='except.throw' title='14.2&emsp;Throwing an exception'>[except.<span class='shy'></span>throw]</a>), or</li><li id='except.terminate-1.9'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.9'>(1.9)</a></div>when the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>nested_<span class='shy'></span>exception<span class='operator'>&#x200b;::&#x200b;</span>rethrow_<span class='shy'></span>nested</span> is called for an object
that has captured no exception (<a href='except.nested' title='17.9.8&emsp;nested_&shy;exception'>[except.<span class='shy'></span>nested]</a>), or</li><li id='except.terminate-1.10'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.10'>(1.10)</a></div>when execution of the initial function of a thread exits via
an exception (<a href='thread.thread.constr' title='32.4.3.3&emsp;Constructors'>[thread.<span class='shy'></span>thread.<span class='shy'></span>constr]</a>), or</li><li id='except.terminate-1.11'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.11'>(1.11)</a></div>for a parallel algorithm whose <span class='texttt'>ExecutionPolicy</span> specifies such
behavior (<a href='execpol.seq' title='26.3.6.3&emsp;Sequenced execution policy'>[execpol.<span class='shy'></span>seq]</a>, <a href='execpol.par' title='26.3.6.4&emsp;Parallel execution policy'>[execpol.<span class='shy'></span>par]</a>, <a href='execpol.parunseq' title='26.3.6.5&emsp;Parallel and unsequenced execution policy'>[execpol.<span class='shy'></span>parunseq]</a>),
when execution of an element access function (<a href='algorithms.parallel.defns' title='26.3.1&emsp;Preamble'>[algorithms.<span class='shy'></span>parallel.<span class='shy'></span>defns]</a>)
of the parallel algorithm exits via an exception (<a href='algorithms.parallel.exceptions' title='26.3.4&emsp;Parallel algorithm exceptions'>[algorithms.<span class='shy'></span>parallel.<span class='shy'></span>exceptions]</a>), or</li><li id='except.terminate-1.12'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.12'>(1.12)</a></div>when the destructor or the move assignment operator is invoked on an object
of type <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>thread</span> that refers to
a joinable thread (<a href='thread.thread.destr' title='32.4.3.4&emsp;Destructor'>[thread.<span class='shy'></span>thread.<span class='shy'></span>destr]</a>, <a href='thread.thread.assign' title='32.4.3.5&emsp;Assignment'>[thread.<span class='shy'></span>thread.<span class='shy'></span>assign]</a>), or</li><li id='except.terminate-1.13'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.13'>(1.13)</a></div>when a call to a <span class='texttt'>wait<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, <span class='texttt'>wait_<span class='shy'></span>until<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, or <span class='texttt'>wait_<span class='shy'></span>for<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>
function on a condition variable (<a href='thread.condition.condvar' title='32.7.4&emsp;Class condition_&shy;variable'>[thread.<span class='shy'></span>condition.<span class='shy'></span>condvar]</a>, <a href='thread.condition.condvarany' title='32.7.5&emsp;Class condition_&shy;variable_&shy;any'>[thread.<span class='shy'></span>condition.<span class='shy'></span>condvarany]</a>)
fails to meet a postcondition, or</li><li id='except.terminate-1.14'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.14'>(1.14)</a></div>when a callback invocation exits via an exception
when requesting stop on
a <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>stop_<span class='shy'></span>source</span> or
a <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>inplace_<span class='shy'></span>stop_<span class='shy'></span>source</span> (<a href='stopsource.mem' title='32.3.5.3&emsp;Member functions'>[stopsource.<span class='shy'></span>mem]</a>, <a href='stopsource.inplace.mem' title='32.3.9.3&emsp;Member functions'>[stopsource.<span class='shy'></span>inplace.<span class='shy'></span>mem]</a>),
or in the constructor of
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>stop_<span class='shy'></span>callback</span> or
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>inplace_<span class='shy'></span>stop_<span class='shy'></span>callback</span> (<a href='stopcallback.cons' title='32.3.6.2&emsp;Constructors and destructor'>[stopcallback.<span class='shy'></span>cons]</a>, <a href='stopcallback.inplace.cons' title='32.3.10.2&emsp;Constructors and destructor'>[stopcallback.<span class='shy'></span>inplace.<span class='shy'></span>cons]</a>)
when a callback invocation exits via an exception, or</li><li id='except.terminate-1.15'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.15'>(1.15)</a></div>when a <span class='texttt'>run_<span class='shy'></span>loop</span> object is destroyed
that is still in the <span class='texttt'>running</span> state (<a href='exec.run.loop' title='33.12.1&emsp;execution&#x200b;::&#x200b;run_&shy;loop'>[exec.<span class='shy'></span>run.<span class='shy'></span>loop]</a>), or</li><li id='except.terminate-1.16'><div class='marginalizedparent' style='left:-27mm'><a class='marginalized' href='#except.terminate-1.16'>(1.16)</a></div>when <span class='texttt'>unhandled_<span class='shy'></span>stopped</span> is called on
a <span class='texttt'>with_<span class='shy'></span>awaitable_<span class='shy'></span>senders<span class='anglebracket'>&lt;</span>T<span class='anglebracket'>&gt;</span></span> object (<a href='exec.with.awaitable.senders' title='33.13.2&emsp;execution&#x200b;::&#x200b;with_&shy;awaitable_&shy;senders'>[exec.<span class='shy'></span>with.<span class='shy'></span>awaitable.<span class='shy'></span>senders]</a>)
whose continuation is not a handle to a coroutine
whose promise type has an <span class='texttt'>unhandled_<span class='shy'></span>stopped</span> member function<a class='hidden_link' href='#except.terminate-1.sentence-3'>.</a></li></ul></div> —&nbsp;<i>end note</i>]</div></div></div></div><div class='para' id='except.terminate-2'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/399b93910d0bb6f5632405ad188e9f4aad0ae99a/source/exceptions.tex#L1105'>#</a></div><div class='texpara'><div id='except.terminate-2.sentence-1' class='sentence'><a class='index' id=':terminate_'></a>In the situation where no matching handler is found, it is
<a class='index' id=':stack_unwinding_before_invocation_of_std::terminate'></a>implementation-defined
whether or not the stack is unwound
before <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is invoked<a class='hidden_link' href='#except.terminate-2.sentence-1'>.</a></div> <div id='except.terminate-2.sentence-2' class='sentence'>In the situation where the search for a handler (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>) encounters the
outermost block of a function
with a non-throwing exception specification (<a href='except.spec' title='14.5&emsp;Exception specifications'>[except.<span class='shy'></span>spec]</a>), it is
<a class='index' id=':whether_stack_is_unwound_before_invoking_the_function_std::terminate_when_a_noexcept_specification_is_violated'></a>implementation-defined
whether the stack is unwound, unwound partially, or not unwound at all
before the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is invoked<a class='hidden_link' href='#except.terminate-2.sentence-2'>.</a></div> <div id='except.terminate-2.sentence-3' class='sentence'>In all other situations, the stack shall not be unwound before
the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span>
is invoked<a class='hidden_link' href='#except.terminate-2.sentence-3'>.</a></div> <div id='except.terminate-2.sentence-4' class='sentence'>An implementation is not permitted to finish stack unwinding
prematurely based on a determination that the unwind process
will eventually cause an invocation of the function
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span><a class='hidden_link' href='#except.terminate-2.sentence-4'>.</a></div></div></div></div><div id='except.uncaught' class='section'><h3 ><a class='secnum' href='#except.uncaught' style='min-width:80pt'>14.6.3</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_<span class='shy'></span>exceptions</span> function <a class='abbr_ref' href='except.uncaught'>[except.uncaught]</a></h3><div class='texpara'><a class='index' id='lib:uncaught_exceptions'></a></div><div class='para' id='except.uncaught-1'><div class='marginalizedparent'><a class='marginalized' href='#except.uncaught-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/399b93910d0bb6f5632405ad188e9f4aad0ae99a/source/exceptions.tex#L1129'>#</a></div><div class='texpara'><div id='except.uncaught-1.sentence-1' class='sentence'>An exception is considered uncaught
after completing the initialization of the <a href='except.throw#def:exception_handling,exception_object' title='14.2&emsp;Throwing an exception&emsp;[except.throw]'>exception object</a>
until completing the activation of a handler for the exception (<a href='except.handle' title='14.4&emsp;Handling an exception'>[except.<span class='shy'></span>handle]</a>)<a class='hidden_link' href='#except.uncaught-1.sentence-1'>.</a></div> <div id='except.uncaught-note-1' class='note'><div class='texpara'>[<i>Note&nbsp;<a href='#except.uncaught-note-1'>1</a></i>:&ensp;<div id='except.uncaught-1.sentence-2' class='sentence'>As a consequence, an exception is considered uncaught
during any stack unwinding resulting from it being thrown<a class='hidden_link' href='#except.uncaught-1.sentence-2'>.</a></div> —&nbsp;<i>end note</i>]</div></div> <div id='except.uncaught-1.sentence-3' class='sentence'>
If an exception is rethrown (<a href='expr.throw' title='7.6.18&emsp;Throwing an exception'>[expr.<span class='shy'></span>throw]</a>, <a href='propagation' title='17.9.7&emsp;Exception propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught<a class='hidden_link' href='#except.uncaught-1.sentence-3'>.</a></div> <div id='except.uncaught-1.sentence-4' class='sentence'>The function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>uncaught_<span class='shy'></span>exceptions</span> (<a href='uncaught.exceptions' title='17.9.6&emsp;uncaught_&shy;exceptions'>[uncaught.<span class='shy'></span>exceptions]</a>)
returns the number of uncaught exceptions in the current thread<a class='hidden_link' href='#except.uncaught-1.sentence-4'>.</a></div> </div></div></div></div></body></html>